### ISSUE TITLE
Reporte de la |Dll implementada en calculadora|

### ISSUE THREAD

**Issue by KarlaV0** [SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-KarlaV0#2]
[TAP,Unidad 2,Reporte 1,Libreria,KarlaVO.pdf](https://github.com/SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-KarlaV0/files/6341089/TAP.Unidad.2.Reporte.1.Libreria.KarlaVO.pdf)

**Comment by Brisa-4** [comment]
[2.- Rúbrica reporte de practica.pdf](https://github.com/SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-KarlaV0/files/6366760/2.-.Rubrica.reporte.de.practica.pdf)

**Comment by Brisa-4** [comment]
20/20
Calificó Brisa Osorio Ramírez

**Comment by josealfredo79** [comment]
Bien hecho y revisado
